"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { cn } from "@/lib/utils";
import { Scale, Shield, Users, CreditCard, Sparkles, AlertTriangle, Cpu, Gavel, Lock, Handshake } from "lucide-react";

const SECTIONS = [
  { id: "preamble", title: "Preamble & Definitions", icon: Scale },
  { id: "service-protocols", title: "Service & Quality Standards", icon: Sparkles },
  { id: "financial", title: "Financial & Pricing", icon: CreditCard },
  { id: "guild", title: "The Specialist Guild", icon: Users },
  { id: "restrictive", title: "Non-Solicitation & Covenants", icon: Handshake }, // NEW
  { id: "confidentiality", title: "Confidentiality & NDA", icon: Lock }, // NEW
  { id: "displacement", title: "Displacement & Perks", icon: Sparkles },
  { id: "access", title: "Access & Security", icon: Shield },
  { id: "liability", title: "Liability & Damages", icon: AlertTriangle },
  { id: "future", title: "Future Technologies", icon: Cpu },
  { id: "governance", title: "Governance & CPA", icon: Gavel },
];

export default function TermsPage() {
  const [activeSection, setActiveSection] = useState("preamble");

  const scrollTo = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      element.scrollIntoView({ behavior: "smooth", block: "start" });
      setActiveSection(id);
    }
  };

  return (
    <div className="container mx-auto px-6 lg:px-12">
      
      <div className="mb-16 border-b border-cereniti-200 pb-8">
        <h1 className="font-serif text-4xl md:text-6xl text-cereniti-900">
          Terms of <span className="italic text-olive-600">Engagement.</span>
        </h1>
        <p className="mt-4 text-cereniti-500 max-w-2xl leading-relaxed">
          The constitution governing the relationship between Cereniti, our Members (Clients), and the Specialist Guild. 
          Effective Date: January 7, 2026.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        
        {/* --- LEFT NAVIGATION (STICKY) --- */}
        <div className="hidden lg:block lg:col-span-3">
          <div className="sticky top-32 space-y-1">
            {SECTIONS.map((section) => (
              <button
                key={section.id}
                onClick={() => scrollTo(section.id)}
                className={cn(
                  "flex items-center gap-3 w-full px-4 py-3 text-sm font-medium rounded-lg transition-all",
                  activeSection === section.id 
                    ? "bg-cereniti-900 text-white shadow-lg" 
                    : "text-cereniti-500 hover:bg-cereniti-100 hover:text-cereniti-900"
                )}
              >
                <section.icon className="h-4 w-4" />
                {section.title}
              </button>
            ))}
          </div>
        </div>

        {/* --- RIGHT CONTENT --- */}
        <div className="lg:col-span-9 space-y-20">
          
          {/* 1. PREAMBLE */}
          <Section id="preamble" title="1. Preamble & Ecosystem Definitions">
            <p>
              Cereniti is not a traditional cleaning company. It is a managed marketplace and lifestyle infrastructure platform. 
              By creating an account, booking a service, or applying as a Specialist, you agree to be bound by these terms.
            </p>
            <ul className="list-disc pl-5 space-y-2 mt-4 text-cereniti-600">
              <li><strong>&quot;The Platform&quot;</strong> refers to the Cereniti web application, algorithms, and booking engines.</li>
              <li><strong>&quot;The Member&quot;</strong> refers to the client utilizing the service for their property.</li>
              <li><strong>&quot;The Specialist&quot;</strong> refers to the independent contractor vetted and deployed by the Guild.</li>
              <li><strong>&quot;Signature Partner&quot;</strong> refers to third-party luxury brands (Spas, Vineyards) providing experiences.</li>
            </ul>
          </Section>

          {/* 2. SERVICE PROTOCOLS */}
          <Section id="service-protocols" title="2. Service Protocols & Quality Standards">
            <h4 className="font-bold text-cereniti-900 mt-4">2.1 The Scope of Work</h4>
            <p>
              Services are strictly limited to the &quot;Ritual&quot; selected during booking. 
              Our specialists are instructed <strong>not to deviate</strong> from the digital checklist assigned to their device. 
            </p>
            
            <h4 className="font-bold text-cereniti-900 mt-4">2.2 The &quot;Binding Estimate&quot;</h4>
            <p>
              Prices generated by our Booking Wizard are estimates based on provided data. If the on-site condition differs (e.g., &quot;Post-Renovation&quot; dust declared as &quot;Standard&quot;), Cereniti reserves the right to revise the fee prior to commencement.
            </p>

            <h4 className="font-bold text-cereniti-900 mt-4 text-red-600">2.3 The Aesthetic Standard (Breach of Protocol)</h4>
            <p>
              Cereniti adheres to a proprietary <strong>&quot;Signature Scent & Fold&quot;</strong> protocol. 
              Failure by a Specialist to adhere to these specific finishing standards constitutes a material breach of quality. 
              Repeated failure will result in immediate removal from the Platform to preserve the integrity of the Guild.
            </p>
          </Section>

          {/* 3. FINANCIAL */}
          <Section id="financial" title="3. Financial Framework">
            <h4 className="font-bold text-cereniti-900 mt-4">3.1 Dynamic Pricing Engine</h4>
            <p>
              Our fees are algorithmic, calculated based on volume, surface complexity (pH requirements), and intensity. 
              A minimum engagement fee applies to all deployments.
            </p>

            <h4 className="font-bold text-cereniti-900 mt-4">3.2 Payment & Holds</h4>
            <p>
              Payment is secured via credit card authorization 24 hours prior to deployment. Funds are captured only upon successful &quot;Handover&quot;.
            </p>
          </Section>

          {/* 4. THE GUILD (CONTRACTORS) */}
          <Section id="guild" title="4. The Specialist Guild (Contractor Model)">
            <div className="bg-olive-50 border border-olive-200 p-4 rounded-lg my-4">
              <p className="text-sm text-olive-800 font-medium">
                <strong>Crucial for Labor Law compliance:</strong>
              </p>
            </div>
            <p>
              Specialists operating on the Cereniti Platform are <strong>Independent Contractors</strong>, not employees. 
              They retain full autonomy to accept or decline job broadcasts. They utilize Cereniti purely as a lead generation, administrative, and logistical support platform.
            </p>
          </Section>

          {/* 5. RESTRICTIVE COVENANTS (NEW) */}
          <Section id="restrictive" title="5. Non-Circumvention & Non-Solicitation">
            <div className="bg-red-50 border-l-4 border-red-500 p-4 my-4">
              <p className="text-red-900 text-sm font-bold">
                 This clause is strictly enforced to protect the integrity of the Platform.
              </p>
            </div>
            <p>
              <strong>5.1 Non-Solicitation:</strong> The Specialist agrees not to solicit, offer services to, or accept direct employment from any Cereniti Member introduced via the Platform.
            </p>
            <p className="mt-4">
              <strong>5.2 Duration:</strong> This restriction applies during the active engagement with Cereniti and extends for a period of <strong>24 months</strong> following the termination of the Specialist&apos;s access to the Platform.
            </p>
            <p className="mt-4">
              <strong>5.3 Penalty:</strong> Any attempt to circumvent the Platform (e.g., offering cash deals to Members) will result in immediate permanent banning, forfeiture of pending commissions, and potential legal action for damages.
            </p>
          </Section>

          {/* 6. CONFIDENTIALITY (NEW) */}
          <Section id="confidentiality" title="6. The Privacy Fortress (NDA)">
            <p>
              By accessing a Member&apos;s home, the Specialist enters a strict Non-Disclosure Agreement (NDA).
            </p>
            <ul className="list-disc pl-5 space-y-3 mt-4 text-cereniti-600">
              <li><strong>Visual Privacy:</strong> The Specialist shall not photograph, record, or document any details of the Client&apos;s residence, lifestyle, personal belongings, or documents, except for the specific &quot;Quality Control&quot; photos required by the App.</li>
              <li><strong>Lifestyle Discretion:</strong> Information regarding the Member&apos;s presence, habits, guests, or conversations overheard on-site is classified as strictly confidential.</li>
              <li><strong>Zero Tolerance:</strong> Breach of this privacy protocol results in immediate legal recourse.</li>
            </ul>
          </Section>

          {/* 7. DISPLACEMENT PROTOCOL */}
          <Section id="displacement" title="7. Displacement & Signature Partners">
            <p>
              Certain premium tiers unlock complimentary lifestyle benefits via our &quot;Signature Experience Partners&quot; (e.g., Spas, Vineyards).
            </p>
            <ul className="list-disc pl-5 space-y-2 mt-4 text-cereniti-600">
              <li><strong>Availability:</strong> Perks are subject to Partner availability. Cereniti acts as the booking agent.</li>
              <li><strong>Third-Party Liability:</strong> We are not liable for the service quality or injury provided by third-party partners.</li>
              <li><strong>Voucher Redemption:</strong> Experience Credits are purchased by Cereniti on behalf of the Member and are non-transferable.</li>
            </ul>
          </Section>

          {/* 8. ACCESS & SECURITY */}
          <Section id="access" title="8. Access, Security & Logistics">
            <h4 className="font-bold text-cereniti-900 mt-4">8.1 Biometric & Estate Access</h4>
            <p>
              The Member acts as the &quot;Host.&quot; It is the Member&apos;s responsibility to generate access codes for the Cereniti Logistics Shuttle. 
              Delays caused by gate access issues (&gt;15 minutes) will incur a waiting fee.
            </p>
          </Section>

          {/* 9. LIABILITY */}
          <Section id="liability" title="9. Liability, Breakage & Luxury Finishes">
            <h4 className="font-bold text-cereniti-900 mt-4">9.1 The &quot;High Care&quot; Clause</h4>
            <p>
              The Member <strong>must</strong> declare the presence of sensitive materials via the &quot;Luxury Finishes Protocol&quot; toggle.
              If these surfaces are NOT declared, Cereniti is indemnified against damage caused by standard cleaning agents.
            </p>
          </Section>

          {/* 10. FUTURE TECH */}
          <Section id="future" title="10. Future Systems & Data">
            <p>
              Cereniti reserves the right to implement advanced monitoring technologies.
            </p>
            <ul className="list-disc pl-5 space-y-2 mt-4 text-cereniti-600">
              <li><strong>Quality Control Leads:</strong> Senior supervisors may perform random site audits to ensure the &quot;Premium Feel&quot; is consistent.</li>
              <li><strong>IoT Integration:</strong> We may integrate with Smart Home APIs for seamless access.</li>
              <li><strong>AI Training:</strong> Anonymized imagery may be used to train Computer Vision models.</li>
            </ul>
          </Section>

          {/* 11. GOVERNANCE */}
          <Section id="governance" title="11. Governance & Jurisdiction">
            <p>
              These terms are governed by the laws of the Republic of South Africa. 
              Disputes fall under the jurisdiction of the Western Cape High Court.
            </p>
          </Section>

        </div>
      </div>
    </div>
  );
}

// --- HELPER COMPONENT ---
function Section({ id, title, children }: { id: string, title: string, children: React.ReactNode }) {
  return (
    <motion.section 
      id={id}
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-100px" }}
      className="scroll-mt-32"
    >
      <h3 className="font-serif text-2xl text-cereniti-900 border-b border-cereniti-200 pb-4 mb-6">
        {title}
      </h3>
      <div className="text-cereniti-600 leading-7 space-y-4">
        {children}
      </div>
    </motion.section>
  );
}